# Generated by Django 3.0.4 on 2020-12-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201217_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
